language: C
sudo: true
compiler:
  - gcc

addons:
  apt:
    packages:
      - nasm
      - build-essential
      - bison
      - flex
      - libgmp3-dev
      - libmpc-dev
      - libmpfr-dev
      - texinfo
      - libcloog-isl-dev
      - libisl-dev
      - wget
      - clang
      - xorriso
      - mtools
      - efibootmgr
      - dosfstools

env:
  global:
    - TARGET="i686-elf"

matrix:
  include:
    - name: Release
      env: RELEASE=true  GCC_VERSION="5.4.0" BINUTILS_VERSION="2.29"
    - name: Debug
      env: RELEASE=false GCC_VERSION="5.4.0" BINUTILS_VERSION="2.29"
    - name: Latest GCC and Binutils
      env: RELEASE=false GCC_VERSION="9.1.0" BINUTILS_VERSION="2.32"
  allow_failures:
    - name: Latest GCC and Binutils

install:
  - travis_wait make deps
  - make

script:
  - make test
  - make lint

cache:
  apt: true
  directories:
    - .deps

before_deploy:
  - scripts/deploy.sh

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file: "$RELEASE_FILE_NAME"
  skip_cleanup: true
  draft: true
  overwrite: true
  on:
    branch: disk_release
