language: C
sudo: true
compiler:
  - gcc

addons:
  apt:
    packages:
      - nasm
      - build-essential
      - bison
      - flex
      - libgmp3-dev
      - libmpc-dev
      - libmpfr-dev
      - texinfo
      - libcloog-isl-dev
      - libisl-dev
      - wget

install:
  - travis_wait make deps
  - make

script:
  - make test

cache:
  apt: true
  directories:
    - .deps
