language: C
sudo: true
compiler:
  - gcc

addons:
  apt:
    packages:
      - nasm
      - build-essential
      - bison
      - flex
      - texinfo
      - wget
      - clang
  homebrew:
    packages:
      - nasm
      - wget


env:
  global:
    - TARGET="i686-elf"

matrix:
  include:
    - name: Release
      env: RELEASE=true  GCC_VERSION="5.4.0" BINUTILS_VERSION="2.29"
    - name: Debug
      env: RELEASE=false GCC_VERSION="5.4.0" BINUTILS_VERSION="2.29"
    - name: MacOS
      os: osx
      env: RELEASE=false GCC_VERSION="5.4.0" BINUTILS_VERSION="2.29"
    - name: Latest GCC and Binutils
      env: RELEASE=false GCC_VERSION="9.1.0" BINUTILS_VERSION="2.32"
  allow_failures:
    - name: Latest GCC and Binutils

install:
  - travis_wait 60 make deps
  - make

script:
  - make test
  - make lint

cache:
  apt: true
  directories:
    - .deps
