name: Build

on: [push]

jobs:
    build_linux:
        name: Build on Linux
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Install dependencies
              run: sudo apt-get install build-essential nasm flex bison texinfo wget
            - name: Build cross compiler
              run: make deps
            - name: Compile
              run: make
